name: Convert models from HF to GGUF

on:
    workflow_dispatch:
 
jobs:
    convert-model:
        runs-on: model-factory-runner
        strategy:
            matrix:
                model:
                    - repo: meta-llama/Llama-2-7b-chat
                      name: llama-2
                      variant: 7b-chat
                      description: "Llama 2 7b chat model"
                      kitfile-template: ./kitfiles/llama2.yml
                      qnt: f16

        env:
            HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
            HF_HUB_ENABLE_HF_TRANSFER: 1
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Install dependencies
              run:  |
                ./scripts/check-hf-cli 
                ./scripts/check-convert
            - name: download model
              run: ./scripts/hf-clone ${{ matrix.model.repo }} ./model
            - name: check diskspace after download
              run: | 
                echo "Disk space after base model downloads:"
                df -h
            - name: convert model to gguf
              run: ./scripts/conv-to-gguf ./model ./model/${{matrix.model.name}}-${{matrix.model.variant}}-${{matrix.model.qnt}}.gguf
            - name: generate kitfile
              run: | 
                  ./scripts/update-kitfile "${{matrix.model.name}}-${{matrix.model.variant}}-${{matrix.model.qnt}}" \
                  "${{matrix.model.description}}" ./${{matrix.model.name}}-${{matrix.model.variant}}-${{matrix.model.qnt}}.gguf \
                  ${{matrix.model.kitfile-template}} ./model/kitfile
            - uses: jozu-ai/gh-kit-setup@v1.0.0
              name: install kit CLI
            - name: login to kit
              run: kit login --username ${{github.actor}} --password ${{secrets.GITHUB_TOKEN}}
            - name: pack modelkit
              run: kit pack ./model -t ghcr.io/jozu-ai/${{matrix.model.name}}:${{matrix.model.variant}}-${{matrix.model.qnt}}
            - name: push modelkit
              run: kit push ghcr.io/jozu-ai/${{matrix.model.name}}:${{matrix.model.variant}}-${{matrix.model.qnt}}
        
                