name: Clone Repository

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    clone:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  repository: https://huggingface.co/meta-llama/Llama-2-7b
                  lfs: true
