name: Quantize ModelKit

on:
  workflow_dispatch:
      inputs:
          model_name:
              type: string
              description: 'Model name'
              required: true
          model_variant:
              type: string
              description: 'Model variant'
              required: true
          model_parameters:
              type: string
              description: 'Model parameter size'
              required: true
          model_src_qnt:
              type: string
              description: 'Model quantization'
              required: true
              default: 'f16'
          model_target_qnt:
                type: string
                description: 'Model quantization'
                required: true
                default: 'f16'
          model_description:
              type: string
              description: 'Model description'
              required: true
          kitfile_template:
              type: string
              description: 'Kitfile template'
              required: true
          runner: 
              type: string
              description: 'Runner'
              required: true
              default: 'model-factory-runner'

jobs:
    quantize-model:
        runs-on: ${{ inputs.runner }}
        permissions:
          contents: read
          packages: write
        strategy:
            matrix:
                qnt: ${{ fromJSON(inputs.model_target_qnt) }}
        steps:
            - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
              with:
                egress-policy: audit
            - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
              with:
                fetch-depth: 0
            - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
              with:
                python-version: '3.10'
            - name: Install quantize dependencies
              run: ./scripts/check-quantize
            - uses: jozu-ai/gh-kit-setup@1960d89a6396444d03ad93abc1a74a4cf14baccd # v1.0.0
              name: install kit CLI
            - name: login to kit
              run: kit login ghcr.io --username ${{secrets.KIT_USER}} --password ${{secrets.KIT_PASSWORD}}
            - name: unpack base-modelkit
              run: |
                mkdir ./model
                kit pull ghcr.io/jozu-ai/${{inputs.model_name}}:${{inputs.model_parameters}}-${{inputs.model_variant}}-${{inputs.model_src_qnt}}
                kit unpack ghcr.io/jozu-ai/${{inputs.model_name}}:${{inputs.model_parameters}}-${{inputs.model_variant}}-${{inputs.model_src_qnt}} -d ./model
            - name: quantize model
              run: |
                ./scripts/quantize ./model/${{inputs.model_name}}-${{inputs.model_parameters}}-${{inputs.model_variant}}-${{inputs.model_src_qnt}}.gguf \
                ./model/${{inputs.model_name}}-${{inputs.model_parameters}}-${{inputs.model_variant}}-${{matrix.qnt}}.gguf ${{matrix.qnt}}
            - name: generate kitfile
              run: |
                ./scripts/update-kitfile "${{inputs.model_name}}-${{inputs.model_parameters}}-${{inputs.model_variant}}-${{matrix.qnt}}" \
                "${{inputs.model_description}}" ./${{inputs.model_name}}-${{inputs.model_parameters}}-${{inputs.model_variant}}-${{matrix.qnt}}.gguf \
                ${{inputs.kitfile_template}} ./model/Kitfile
                cat ./model/Kitfile
            - name: pack modelkit
              run: |
                kit pack ./model -t ghcr.io/jozu-ai/${{inputs.model_name}}:${{inputs.model_parameters}}-${{inputs.model_variant}}-${{matrix.qnt}} -v
            - name: push modelkit
              run: kit push ghcr.io/jozu-ai/${{inputs.model_name}}:${{inputs.model_parameters}}-${{inputs.model_variant}}-${{matrix.qnt}} -v
