name: Quantize the Model and Pack ModelKit

on:
    workflow_dispatch:
        inputs:
            model-name:
                type: string
                description: 'Model name'
                required: true
            model-variant:
                type: string
                description: 'Model variant'
                required: true
            model-qnt:
                type: string
                description: 'Model quantization'
                required: true
                default: 'f16'
            model-description:
                type: string
                description: 'Model description'
                required: true
            kitfile-template:
                type: string
                description: 'Kitfile template'
                required: true

jobs:
    quantize-model:
        runs-on: model-factory-runner
        permissions: 
          contents: read
          packages: write   
        strategy:
            matrix:
                # qnt: [q8_0,  q6_k,  q5_k,  q5_1,  q5_0,  q4_k,  q4_1,  q4_0,  q3_k,  q2_k]
                qnt: [q8_0,  q5_0,  q4_0]
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Install quantize dependencies
              run: ./scripts/check-quantize
            - uses: jozu-ai/gh-kit-setup@v1.0.0
              name: install kit CLI
            - name: login to kit
              run: kit login ghcr.io --username ${{secrets.KIT_USER}} --password ${{secrets.KIT_PASSWORD}}
            - name: unpack base-modelkit
              run: |
                mkdir ./model
                kit unpack ghcr.io/jozu-ai/${{inputs.model-name}}:${{inputs.model-variant}}-${{inputs.model-qnt}} -d ./model
            - name: quantize model
              run: |
                ./scripts/quantize ./model/${{inputs.model-name}}-${{inputs.model-variant}}-${{inputs.model-qnt}}.gguf \
                ./model/${{inputs.model-name}}-${{inputs.model-variant}}-${{matrix.qnt}}.gguf ${{matrix.qnt}}
            - name: generate kitfile
              run: | 
                ./scripts/update-kitfile "${{inputs.model-name}}-${{inputs.model-variant}}-${{matrix.qnt}}" \
                "${{inputs.model-description}}" ./${{inputs.model-name}}-${{inputs.model-variant}}-${{matrix.qnt}}.gguf \
                ${{inputs.kitfile-template}} ./model/kitfile
            - name: pack modelkit
              run: kit pack ./model -t ghcr.io/jozu-ai/${{inputs.model-name}}:${{inputs.model-variant}}-${{matrix.qnt}}
            - name: push modelkit
              run: kit push ghcr.io/jozu-ai/${{inputs.model-name}}:${{inputs.model-variant}}-${{matrix.qnt}}